const userTypes = {
  SIGNIN_EMAIL_START: 'SIGNIN_EMAIL_START',
  SIGNIN_EMAIL_SUCCESS: 'SIGNIN_EMAIL_SUCCESS',
  SIGNIN_EMAIL_FAILURE: 'SIGNIN_EMAIL_FAILURE',
  REGISTRATION_EMAIL_START: 'REGISTRATION_EMAIL_START',
  REGISTRATION_EMAIL_SUCCESS: 'REGISTRATION_EMAIL_SUCCESS',
  REGISTRATION_EMAIL_FAILURE: 'REGISTRATION_EMAIL_FAILURE',
  SIGNOUT: 'SIGNOUT'
};

export default userTypes;